FROM fedora:latest

MAINTAINER svr93

RUN dnf -y install findutils
RUN dnf -y install which
RUN dnf -y install tar
RUN dnf -y install xz
RUN dnf -y install net-tools

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash && \
    source ~/.bashrc && \
    nvm install v5.2 && nvm alias default node
